export const content = {
  pt: {
    navHow: 'Como funciona',
    navFeatures: 'Recursos',
    navPricing: 'Planos',
    navFaq: 'Perguntas',
    navContact: 'Fale Conosco',
    navCta: 'Entrar',
    navOpenMenu: 'Abrir menu',
    navCloseMenu: 'Fechar menu',
    heroBadge: 'Disponível agora no navegador',
    heroTitle: 'Seu tempo. Sua rotina. Sua conexão com Deus.',
    heroSubtitle: 'O app pra ler a Bíblia com constância: um plano no seu ritmo, oração guiada todo dia e um tempo de qualidade só seu com Deus — sem pressa, sem distração.',
    heroCtaPrimary: 'Começar agora',
    heroCtaSecondary: 'Ver como funciona',
    heroNote: 'Funciona no navegador, sem instalação. Em breve na Play Store e App Store.',
    // Redesign 1h — barra fixa discreta, única outra chamada além do Hero
    // e da Pricing (ver StickyCtaBar em App.jsx).
    stickyBarText: 'Pronto pra começar sua leitura?',
    stickyBarBtn: 'Começar agora',
    mockSessionLabel: 'Tela de leitura do app, com o texto bíblico completo',
    // Etapa 3 (Bento) — "Como funciona": texto puro, sem cartão. Cada
    // passo ganha um campo de tempo (time) que não existia antes — o
    // quadrado laranja mostra o número do passo, o tempo fica ao lado.
    howEyebrow: 'Como funciona',
    howTitle: 'Três passos, todo dia',
    howSubtitle: 'Oração, leitura e reflexão — cada um abre o próximo sozinho, sem voltar pro menu. Você escolhe o tempo de cada passo.',
    howSteps: [
      { time: '10 min', title: 'Oração', desc: 'Roteiro ACTS — Adoração, Confissão, Gratidão e Súplica — com temporizador que avança sozinho de etapa em etapa.' },
      { time: '15 min', title: 'Leitura', desc: 'O capítulo do dia, no seu ritmo — com contexto histórico, marcação de trechos e a opção de ouvir em voz alta.' },
      { time: '5 min', title: 'Reflexão', desc: 'Feche o dia em três perguntas curtas — Reviver, Entender e Aplicar — com o que Deus falou com você na leitura.' },
    ],
    // Redesign 1h — "Por que fiz o app": propósito + origem do nome
    // fundidos num parágrafo só, em primeira pessoa (antes eram duas seções
    // separadas, Purpose e AboutName).
    whyEyebrow: 'Por que fiz o app',
    whyTitle: 'A história de amor mais bonita já contada — e ela é pra todo mundo.',
    whyBody: 'Criei o Jesus\' Corner porque a Bíblia conta a história de um Deus que ama, busca e nunca desiste do Seu povo — do Éden até a eternidade — e eu queria uma forma simples de voltar a essa história todo dia. O nome vem de um "quarto": o lugar que Jesus descreve em Mateus 6, um cantinho só seu, sem plateia, sem comparação, só você, a Bíblia e Deus. Não é sobre grandes gestos religiosos — é sobre abrir esse espaço todo dia, no seu tempo, pra um tempo de qualidade que é só seu.',
    whyVerseText: 'Mas, quando orarem, cada um vá para seu quarto, feche a porta e ore a seu Pai, em segredo. Então seu Pai, que observa em segredo, os recompensará.',
    whyVerseRef: 'Mateus 6:6 · Nova Versão Transformadora (NVT)',
    whyLinkText: 'Comece o seu cantinho agora',
    purposeEyebrow: 'Nosso propósito',
    purposeTitle: 'A história de amor mais bonita já contada.',
    purposeSubtitle: 'E ela é pra todo mundo.',
    purposeBody: 'A Bíblia conta a história de um Deus que ama, busca e nunca desiste do Seu povo — do Éden até a eternidade. O Jesus\' Corner existe pra te aproximar dessa história todos os dias, com uma plataforma completa pra acompanhar sua caminhada de leitura.',
    aboutNameEyebrow: 'A origem do nome',
    aboutNameTitle: 'Por que "Jesus\' Corner"?',
    aboutNameVerseText: 'Mas, quando orarem, cada um vá para seu quarto, feche a porta e ore a seu Pai, em segredo. Então seu Pai, que observa em segredo, os recompensará.',
    aboutNameVerseRef: 'Mateus 6:6 · Nova Versão Transformadora (NVT)',
    aboutNameBody: 'O nome nasce desse "quarto": um cantinho só seu, sem plateia, sem comparação — só você, a Bíblia e Deus. Não é sobre grandes gestos religiosos, é sobre criar esse espaço todo dia, no seu tempo, pra um tempo de qualidade que é só seu.',
    ctaPurposeText: 'Comece hoje mesmo — o primeiro passo é só seu.',
    ctaPurposeBtn: 'Começar agora',
    ctaAboutNameText: 'Seu cantinho com Deus está a um clique de distância.',
    ctaAboutNameBtn: 'Criar meu cantinho',
    // Etapa 4 (Bento) — "Direto do app": 3 pares (era 5, sem cartão de
    // destaque em nenhum). O par do meio (progresso) inverte a ordem
    // (imagem à esquerda no desktop) — ver `order` em index.css/App.jsx.
    // `body` é sempre um array (1 ou 2 parágrafos, o de progresso tem 2).
    showcaseEyebrow: 'Direto do app',
    showcase: [
      {
        image: 'hoje',
        alt: 'Tela Hoje do app: passo atual, sequência e semana',
        title: 'Sua rotina com Deus, num só lugar',
        body: ['Oração, leitura e reflexão numa linha do tempo que se preenche conforme você avança. Toque em iniciar e ela se conduz sozinha, um passo abrindo o próximo — ou faça tudo só ouvindo, no modo mãos-livres.'],
        bullets: ['Cada passo com o seu próprio tempo', 'Meta da semana, nunca sequência quebrada', 'Pule um passo sem perder o dia'],
      },
      {
        image: 'progresso',
        alt: 'Tela de progresso pela Bíblia inteira',
        title: 'Veja seu progresso pela Bíblia inteira',
        body: [
          'A constância das últimas nove semanas abre a tela, seguida dos três números que só sobem — capítulos lidos, horas de leitura e livros concluídos. Abaixo, onde você está no livro e no bloco, com a fatia da Bíblia inteira já percorrida.',
          'Um mês fraco não apaga nada: o app mostra que você voltou, não quantos dias você perdeu.',
        ],
      },
      {
        image: 'plano',
        alt: 'Tela Meu Plano do app, com os três passos do dia',
        title: 'O plano mostra só o dia de hoje',
        body: ['Nada de calendário cheio de dias perdidos: o passo feito fica em areia, o de agora em preto, o que vem depois fica discreto. A semana aparece no fim como resumo, não como placar.'],
        link: 'recursos',
      },
    ],
    showcaseLinkText: 'Ver todos os recursos',
    // Etapa 5 (Bento) — "Assistente de leitura", seção nova (bloco escuro
    // full-width, README item 5). Não existia antes — o chat com IA
    // aparecia só como 1 item na grade de Recursos.
    assistantEyebrow: 'Assistente de leitura',
    assistantTitle: 'Pergunte sobre o texto sem sair da leitura',
    assistantBody: 'Selecione um trecho e pergunte. A resposta sempre cita o versículo que a sustenta e indica onde ler mais — se não houver citação no próprio texto, a resposta não sai.',
    assistantChips: ['O que isso significa?', 'Por que sete?', 'Contexto histórico'],
    // Etapa 6 (Bento) — "Recursos": 8 itens em texto puro, sem cartão
    // nem ícone (eram ~20, em cartão com ícone). Item 5 (Estudos
    // guiados) substitui "Estudo indutivo" do .dc.html — essa feature
    // foi removida do app; decisão confirmada com ela.
    featuresTitle: 'Tudo o que você precisa pra ler a Bíblia com constância',
    featuresSubtitle: 'Sem complicação, sem culpa — só um passo de cada vez.',
    features: [
      { title: 'Planos flexíveis', desc: 'Leve, Padrão, Intensivo ou Livre — troque o ritmo quando quiser, sem perder o progresso.' },
      { title: 'Plano cronológico', desc: 'A Bíblia reordenada pela linha do tempo dos acontecimentos, não pela ordem dos livros.' },
      { title: 'Ouça em voz alta', desc: 'Capítulo a capítulo ou em sequência — e o modo mãos-livres conduz a rotina inteira por áudio.' },
      { title: 'Marque e anote', desc: 'Grife um versículo e escreva uma nota só sobre aquele trecho — tudo buscável depois.' },
      { title: 'Estudos guiados', desc: 'Quatro estudos prontos — Pentateuco, Cronologia, Salmos e As Alianças de Deus — com contexto histórico e perguntas de reflexão.' },
      { title: 'Grupos e sala do capítulo', desc: 'Uma sala por capítulo, aberta a quem concluiu. Quem lê em grupo permanece 2,4× mais tempo.' },
      { title: 'Anotações e sermões', desc: 'Notas de leitura, reflexões e sermões com preletor, igreja e textos lidos — num lugar só.' },
      { title: 'Português e inglês', desc: 'Todo o conteúdo bilíngue, incluindo o contexto histórico de cada livro.' },
    ],
    // Etapa 7 (Bento) — "Planos": 3 cartões, sem checkmark (lista de
    // texto puro) e sem selo flutuante — "popular" agora é só a palavra
    // dentro do rótulo do cartão escuro (ver `popular` abaixo).
    // `priceUsd`/`badge` saíam: o toggle PT/EN já troca o bloco de
    // conteúdo inteiro, não precisa mostrar as duas moedas juntas.
    pricingTitle: 'Comece de graça. Desbloqueie quando quiser.',
    pricingSubtitle: 'Valor fixo, mensal ou anual — troque de nível ou cancele quando quiser.',
    pricingPopularTag: 'popular',
    pricingTiers: [
      {
        name: 'Grátis',
        price: 'R$0',
        tagline: 'Pra começar hoje',
        items: [
          'Bíblia inteira — Leve, Padrão, Intensivo ou Livre',
          'Oração e reflexão guiadas',
          'Áudio com a voz do aparelho',
          'Progresso e capítulos lidos',
        ],
        cta: 'Criar conta grátis',
      },
      {
        name: 'Premium',
        price: 'R$12,90',
        per: '/mês',
        tagline: 'ou R$119,90/ano · a experiência completa',
        items: [
          'Tudo do grátis, e mais:',
          'Voz natural e modo mãos-livres',
          'Plano cronológico da Bíblia',
          'Marcações, notas e conquistas',
          'Comunidade: amigos e grupos',
        ],
        cta: 'Assinar Premium',
      },
      {
        name: 'Premium + IA',
        popular: true,
        price: 'R$21,90',
        per: '/mês',
        tagline: 'ou R$199,90/ano · Premium + o assistente',
        items: [
          'Tudo do Premium, e mais:',
          'Perguntas sobre qualquer passagem',
          'Planos e estudos por tema',
          'Contexto antes do capítulo',
          'Perguntas geradas na reflexão',
        ],
        cta: 'Assinar Premium + IA',
      },
    ],
    pricingNote: 'O pagamento é feito pela loja (Google Play / App Store) dentro do app, ou por cartão na versão web. Ninguém precisa de conta para começar a ler.',
    // Etapa 8 (Bento) — "Baixe onde quiser / Lista de espera": 2 colunas
    // independentes, cada uma com seu próprio rótulo — não é mais 1
    // título de seção + cartão do Web App + linha de espera embaixo.
    downloadEyebrow: 'Baixe onde quiser',
    downloadHeading: 'Já disponível na web',
    downloadBody: 'Sem loja de aplicativos, sem espaço extra no celular — instale direto do navegador, com ícone na tela inicial como qualquer outro app.',
    downloadCta: 'Como instalar',
    waitlistEyebrow: 'Lista de espera',
    waitlistText: 'Google Play e App Store estão a caminho — quer ser avisado(a) assim que sair?',
    waitlistPlaceholder: 'seu@email.com',
    waitlistBtn: 'Me avisa',
    waitlistSending: 'Enviando...',
    waitlistSuccess: 'Combinado! Te avisamos assim que o app nativo estiver disponível.',
    waitlistError: 'Não foi possível registrar agora. Tenta de novo em instantes.',
    installTitle: 'Instale o Jesus\' Corner no seu celular',
    installSubtitle: 'Sem loja de aplicativos, sem espaço extra no celular — funciona direto do navegador, com ícone na tela inicial como qualquer outro app.',
    installIosTitle: 'No iPhone (Safari)',
    installIosSteps: [
      'Abra jesuscorner.app no Safari — precisa ser o Safari, outros navegadores do iPhone não mostram essa opção.',
      'Toque no ícone de compartilhar (o quadrado com uma seta pra cima), na barra de baixo.',
      'Role a lista de opções e toque em "Adicionar à Tela de Início".',
      'Toque em "Adicionar", no canto superior direito.',
    ],
    installAndroidTitle: 'No Android (Chrome)',
    installAndroidSteps: [
      'Abra jesuscorner.app no Chrome.',
      'Toque nos três pontinhos, no canto superior direito.',
      'Toque em "Adicionar à tela inicial" (ou "Instalar app", se aparecer).',
      'Confirme tocando em "Adicionar" ou "Instalar".',
    ],
    installCta: 'Abrir o Jesus\' Corner',
    faqTitle: 'Perguntas frequentes',
    faq: [
      { q: 'Preciso pagar pra usar o Jesus\' Corner?', a: 'Não. O plano grátis já dá pra ler a Bíblia inteira em qualquer ritmo, fazer a oração e a reflexão guiadas, ouvir a Bíblia com a voz do aparelho e acompanhar seu progresso. O Premium (R$12,90/mês) acrescenta voz natural, rotina guiada automática, conquistas, plano cronológico, notas e Comunidade; o Premium + IA (R$21,90/mês) acrescenta o assistente de IA — perguntas sobre o texto, planos e estudos gerados. Sem anúncios em nenhum dos planos.' },
      { q: 'Funciona sem internet?', a: 'Sim. Como é um Web App instalável (PWA), o conteúdo já visitado fica salvo no seu dispositivo e funciona offline.' },
      { q: 'Em quais idiomas o app está disponível?', a: 'Português e inglês, com troca de idioma a qualquer momento direto no seu perfil.' },
      { q: 'Qual versão da Bíblia o app usa?', a: 'Hoje o texto bíblico completo já está disponível no app em duas versões licenciadas via API.Bible: Nova Versão Transformadora — NVT (português) e New Living Translation — NLT (inglês). Mais versões serão adicionadas em breve.' },
      { q: 'Vai ter versão nativa na Play Store e App Store?', a: 'Sim, estão em preparação. Enquanto isso, você já pode instalar o Web App na tela inicial do seu celular e usar como um app normal.' },
      { q: 'Meus amigos veem meu progresso de leitura?', a: 'Por padrão, sim — seu perfil já nasce público pros seus amigos, que veem seu progresso geral de leitura, o que você está lendo e seus grupos, além de nome, foto e mensagem. Se preferir mais privacidade, você pode deixar o perfil privado a qualquer momento em Perfil — aí só nome, foto e mensagem continuam visíveis.' },
      { q: 'Tem restrição de idade?', a: 'Sim. O Jesus\' Corner é destinado a maiores de 18 anos — o cadastro pede a idade e barra quem tem menos de 18.' },
    ],
    ctaFaqText: 'Ainda com dúvidas? A melhor forma de saber é experimentando.',
    ctaFaqBtn: 'Experimentar agora',
    contactTitle: 'Fale conosco',
    contactSubtitle: 'Dúvidas, sugestões ou algo não funcionando como devia? Escreva pra gente abaixo.',
    contactNameLabel: 'Nome',
    contactNamePlaceholder: 'Seu nome',
    contactEmailLabel: 'E-mail',
    contactEmailPlaceholder: 'seu@email.com',
    contactMessageLabel: 'Mensagem',
    contactMessagePlaceholder: 'Escreva sua mensagem...',
    contactRequiredError: 'Preencha nome, e-mail e mensagem antes de enviar.',
    contactSubmitBtn: 'Enviar mensagem',
    contactSending: 'Enviando...',
    contactSuccessTitle: 'Mensagem enviada!',
    contactSuccessSub: 'Obrigado por escrever — vamos responder no e-mail que você deixou assim que possível.',
    contactSendAnother: 'Enviar outra mensagem',
    footerTagline: 'Feito com fé, um capítulo de cada vez.',
    footerInstagramLabel: 'Instagram do Jesus\' Corner',
    footerPrivacyLink: 'Política de Privacidade',
    footerTermsLink: 'Termos de Uso',
    footerRights: 'Todos os direitos reservados.',
  },
  en: {
    navHow: 'How it works',
    navFeatures: 'Features',
    navPricing: 'Pricing',
    navFaq: 'FAQ',
    navContact: 'Contact',
    navCta: 'Sign in',
    navOpenMenu: 'Open menu',
    navCloseMenu: 'Close menu',
    heroBadge: 'Available now in your browser',
    heroTitle: 'Your time. Your routine. Your connection with God.',
    heroSubtitle: "The app for reading the Bible consistently: a plan at your pace, guided prayer every day, and quality time that's just yours with God — no rush, no distractions.",
    heroCtaPrimary: 'Get started',
    heroCtaSecondary: 'See how it works',
    heroNote: 'Works right in your browser, no install needed. Coming soon to the Play Store and App Store.',
    stickyBarText: 'Ready to start your reading?',
    stickyBarBtn: 'Get started',
    mockSessionLabel: 'The app reading screen, with the full Bible text',
    howEyebrow: 'How it works',
    howTitle: 'Three steps, every day',
    howSubtitle: 'Prayer, reading, and reflection — each one opens the next on its own, no going back to the menu. You choose how long each step takes.',
    howSteps: [
      { time: '10 min', title: 'Prayer', desc: 'The ACTS routine — Adoration, Confession, Thanksgiving, and Supplication — with a timer that moves through each step on its own.' },
      { time: '15 min', title: 'Reading', desc: "The day's chapter, at your pace — with historical context, passage highlighting, and the option to listen out loud." },
      { time: '5 min', title: 'Reflection', desc: 'Close the day with three short questions — Recall, Understand, and Apply — with what God spoke to you through the reading.' },
    ],
    whyEyebrow: 'Why I built this',
    whyTitle: 'The most beautiful love story ever told — and it\'s for everyone.',
    whyBody: "I built Jesus' Corner because the Bible tells the story of a God who loves, pursues, and never gives up on His people — from Eden to eternity — and I wanted a simple way to come back to that story every day. The name comes from a \"room\": the place Jesus describes in Matthew 6, a corner that's just yours, no audience, no comparison, just you, the Bible, and God. It's not about grand religious gestures — it's about opening that space every day, in your own time, for quality time that's yours alone.",
    whyVerseText: 'But when you pray, go away by yourself, shut the door behind you, and pray to your Father in private. Then your Father, who sees everything, will reward you.',
    whyVerseRef: 'Matthew 6:6 · New Living Translation (NLT)',
    whyLinkText: 'Start your own corner now',
    purposeEyebrow: 'Our purpose',
    purposeTitle: "The most beautiful love story ever told.",
    purposeSubtitle: "And it's for everyone.",
    purposeBody: "The Bible tells the story of a God who loves, pursues, and never gives up on His people — from Eden to eternity. Jesus' Corner exists to bring you closer to that story every day, with a complete platform to track your reading journey.",
    aboutNameEyebrow: 'Where the name comes from',
    aboutNameTitle: 'Why "Jesus\' Corner"?',
    aboutNameVerseText: 'But when you pray, go away by yourself, shut the door behind you, and pray to your Father in private. Then your Father, who sees everything, will reward you.',
    aboutNameVerseRef: 'Matthew 6:6 · New Living Translation (NLT)',
    aboutNameBody: "The name comes from that \"room\": a corner that's just yours, no audience, no comparison — just you, the Bible, and God. It's not about grand religious gestures, it's about creating that space every day, in your own time, for quality time that's yours alone.",
    ctaPurposeText: 'Start today — the first step is yours to take.',
    ctaPurposeBtn: 'Get started',
    ctaAboutNameText: 'Your corner with God is just one click away.',
    ctaAboutNameBtn: 'Create my corner',
    showcaseEyebrow: 'Straight from the app',
    showcase: [
      {
        image: 'hoje',
        alt: "The app's Today screen: current step, streak, and week",
        title: 'Your routine with God, in one place',
        body: ["Prayer, reading, and reflection laid out on a timeline that fills in as you go. Tap start and it runs on its own, each step opening the next — or do it all just by listening, in hands-free mode."],
        bullets: ['Each step keeps its own time', 'A weekly goal, never a broken streak', 'Skip a step without losing the day'],
      },
      {
        image: 'progresso',
        alt: 'Progress screen for the whole Bible',
        title: 'See your progress through the whole Bible',
        body: [
          "The last nine weeks of consistency open the screen, followed by three numbers that only go up — chapters read, hours reading, and books finished. Below that, where you are in the book and in the block, with how much of the whole Bible you've covered.",
          "A weak month erases nothing: the app shows that you came back, not how many days you missed.",
        ],
      },
      {
        image: 'plano',
        alt: "The app's My Plan screen, with the day's three steps",
        title: "The plan shows only today",
        body: ["No calendar full of missed days: the step you finished sits in sand, the current one in black, what's next stays quiet. The week shows up at the end as a summary, not a scoreboard."],
        link: 'recursos',
      },
    ],
    showcaseLinkText: 'See all features',
    assistantEyebrow: 'Reading assistant',
    assistantTitle: 'Ask about the text without leaving your reading',
    assistantBody: "Select a passage and ask. The answer always cites the verse behind it and points to where to read more — if there's no citation in the text itself, no answer comes back.",
    assistantChips: ['What does this mean?', 'Why seven?', 'Historical context'],
    featuresTitle: 'Everything you need to read the Bible consistently',
    featuresSubtitle: 'No complications, no guilt — just one step at a time.',
    features: [
      { title: 'Flexible plans', desc: 'Light, Standard, Intensive, or Free — switch pace anytime, without losing your progress.' },
      { title: 'Chronological plan', desc: 'The Bible reordered by the actual timeline of events, not the order of the books.' },
      { title: 'Listen out loud', desc: 'Chapter by chapter or continuously — and hands-free mode runs your whole routine by audio.' },
      { title: 'Highlight and take notes', desc: 'Highlight a verse and write a note just about that passage — all searchable later.' },
      { title: 'Guided studies', desc: 'Four ready-made studies — Pentateuch, Chronology, Psalms, and The Covenants of God — with historical context and reflection questions.' },
      { title: 'Groups and chapter rooms', desc: 'A room for each chapter, open to anyone who finished it. Reading in a group keeps you reading 2.4× longer.' },
      { title: 'Notes and sermons', desc: 'Reading notes, reflections, and sermon notes with preacher, church, and passages covered — in one place.' },
      { title: 'Portuguese and English', desc: "All content in both languages, including each book's historical context." },
    ],
    pricingTitle: 'Start free. Unlock whenever you want.',
    pricingSubtitle: 'A fixed price, monthly or annual — switch tiers or cancel anytime.',
    pricingPopularTag: 'popular',
    pricingTiers: [
      {
        name: 'Free',
        price: 'US$0',
        tagline: 'To start today',
        items: [
          'The whole Bible — Light, Standard, Intensive, or Free',
          'Guided prayer and reflection',
          'Audio with your device voice',
          'Progress and chapters read',
        ],
        cta: 'Create free account',
      },
      {
        name: 'Premium',
        price: 'US$3.99',
        per: '/mo',
        tagline: 'or US$34.99/yr · the full experience',
        items: [
          'Everything in Free, plus:',
          'Natural voice and hands-free mode',
          'Chronological Bible plan',
          'Highlights, notes, and achievements',
          'Community: friends and groups',
        ],
        cta: 'Get Premium',
      },
      {
        name: 'Premium + AI',
        popular: true,
        price: 'US$7.99',
        per: '/mo',
        tagline: 'or US$74.99/yr · Premium + the assistant',
        items: [
          'Everything in Premium, plus:',
          'Questions about any passage',
          'Theme plans and studies',
          'Context before the chapter',
          'Questions generated during reflection',
        ],
        cta: 'Get Premium + AI',
      },
    ],
    pricingNote: "Payment goes through the store (Google Play / App Store) inside the app, or by card on the web version. No account needed to start reading.",
    downloadEyebrow: 'Get it anywhere',
    downloadHeading: 'Already available on the web',
    downloadBody: 'No app store, no extra space on your phone — install right from your browser, with an icon on your home screen just like any other app.',
    downloadCta: 'How to install',
    waitlistEyebrow: 'Waitlist',
    waitlistText: "Google Play and App Store are on the way — want us to let you know when they're out?",
    waitlistPlaceholder: 'you@email.com',
    waitlistBtn: 'Notify me',
    waitlistSending: 'Sending...',
    waitlistSuccess: "Done! We'll let you know as soon as the native app is available.",
    waitlistError: "Couldn't register right now. Try again in a moment.",
    installTitle: 'Install Jesus\' Corner on your phone',
    installSubtitle: 'No app store, no extra space on your phone — it works straight from your browser, with an icon on your home screen just like any other app.',
    installIosTitle: 'On iPhone (Safari)',
    installIosSteps: [
      'Open jesuscorner.app in Safari — it has to be Safari, other iPhone browsers don\'t show this option.',
      'Tap the share icon (the square with an arrow pointing up) in the bottom bar.',
      'Scroll the list of options and tap "Add to Home Screen".',
      'Tap "Add" in the top-right corner.',
    ],
    installAndroidTitle: 'On Android (Chrome)',
    installAndroidSteps: [
      'Open jesuscorner.app in Chrome.',
      'Tap the three dots in the top-right corner.',
      'Tap "Add to Home screen" (or "Install app", if that shows up instead).',
      'Confirm by tapping "Add" or "Install".',
    ],
    installCta: "Open Jesus' Corner",
    faqTitle: 'Frequently asked questions',
    faq: [
      { q: 'Do I need to pay to use Jesus\' Corner?', a: "No. The free plan already lets you read the whole Bible at any pace, do the guided prayer and reflection, listen to the Bible with your device voice, and track your progress. Premium (US$3.99/mo) adds natural voice, the automatic guided routine, achievements, the chronological plan, notes, and Community; Premium + AI (US$7.99/mo) adds the AI assistant — questions about the text, generated plans and studies. No ads on any plan." },
      { q: 'Does it work without internet?', a: 'Yes. As an installable Web App (PWA), content you\'ve already visited is saved on your device and works offline.' },
      { q: 'What languages is the app available in?', a: 'Portuguese and English, switchable anytime right from your profile.' },
      { q: 'Which Bible version does the app use?', a: 'The full Bible text is already available in the app in two versions licensed through API.Bible: New Living Translation — NLT (English) and Nova Versão Transformadora — NVT (Portuguese). More versions will be added soon.' },
      { q: 'Will there be a native version on the Play Store and App Store?', a: 'Yes, it\'s in the works. In the meantime, you can already install the Web App on your home screen and use it like a regular app.' },
      { q: 'Can my friends see my reading progress?', a: "By default, yes — your profile starts out public to friends, who can see your overall reading progress, what you're currently reading, and your groups, plus your name, photo, and bio. If you'd rather keep it private, you can switch that off anytime in Profile — only your name, photo, and bio stay visible after that." },
      { q: 'Is there an age requirement?', a: "Yes. Jesus' Corner is intended for people 18 and older — signup asks for your age and blocks anyone under 18." },
    ],
    ctaFaqText: 'Still have questions? The best way to find out is to try it.',
    ctaFaqBtn: 'Try it now',
    contactTitle: 'Contact us',
    contactSubtitle: "Questions, suggestions, or something not working right? Write to us below.",
    contactNameLabel: 'Name',
    contactNamePlaceholder: 'Your name',
    contactEmailLabel: 'Email',
    contactEmailPlaceholder: 'you@email.com',
    contactMessageLabel: 'Message',
    contactMessagePlaceholder: 'Write your message...',
    contactRequiredError: 'Fill in your name, email, and message before sending.',
    contactSubmitBtn: 'Send message',
    contactSending: 'Sending...',
    contactSuccessTitle: 'Message sent!',
    contactSuccessSub: "Thanks for writing — we'll reply to the email you left as soon as we can.",
    contactSendAnother: 'Send another message',
    footerTagline: 'Made in faith, one chapter at a time.',
    footerInstagramLabel: "Jesus' Corner on Instagram",
    footerPrivacyLink: 'Privacy Policy',
    footerTermsLink: 'Terms of Use',
    footerRights: 'All rights reserved.',
  },
}
