export const content = {
  pt: {
    navFeatures: 'Recursos',
    navPricing: 'Planos',
    navFaq: 'Perguntas',
    navContact: 'Fale Conosco',
    navCta: 'Entrar',
    navOpenMenu: 'Abrir menu',
    navCloseMenu: 'Fechar menu',
    heroBadge: 'Disponível agora como Web App',
    heroTitle: 'Seu tempo. Sua rotina. Sua conexão com Deus.',
    heroSubtitle: 'Um tempo de qualidade, só seu, com Deus e a Bíblia — sem pressa, sem distração. Oração e leitura estruturadas, todo dia, como parte da sua rotina.',
    heroCtaPrimary: 'Começar agora',
    heroCtaSecondary: 'Ver recursos',
    heroNote: 'Funciona no navegador, sem instalação. Em breve na Play Store e App Store.',
    mockSessionLabel: 'SESSÃO DE HOJE',
    aboutNameEyebrow: 'A origem do nome',
    aboutNameTitle: 'Por que "Jesus\' Corner"?',
    aboutNameVerseText: 'Mas, quando você orar, entre no seu quarto, feche a porta e ore a seu Pai, que está em secreto. Então o seu Pai, que vê em secreto, o recompensará.',
    aboutNameVerseRef: 'Mateus 6:6 · NVI',
    aboutNameBody: 'O nome nasce desse "quarto": um cantinho só seu, sem plateia, sem comparação — só você, a Bíblia e Deus. Não é sobre grandes gestos religiosos, é sobre criar esse espaço todo dia, no seu tempo, pra um tempo de qualidade que é só seu.',
    showcaseEyebrow: 'Direto do app',
    showcase: [
      { image: 'home', title: 'Sua rotina com Deus, todo dia', desc: 'Três passos simples — oração, leitura e reflexão — bem visíveis na tela inicial. Sua sequência de dias só conta quando você completa os três, e um calendário mostra seu histórico completo.' },
      { image: 'rotina', title: 'Configure sua rotina, do seu jeito', desc: 'Escolha o tempo de oração e de reflexão, veja o tempo total do seu dia, e acompanhe os 3 passos numa linha do tempo que se preenche conforme você avança — com um botão pra começar direto pela oração.' },
      { image: 'jornada', title: 'Sua jornada, organizada por Antigo e Novo Testamento', desc: 'Cada bloco da Bíblia — Pentateuco, Livros Históricos, Profetas e mais — mostra os livros que o compõem: é só tocar num livro pra ir direto pra leitura dele. Não sabe onde procurar? Use a busca pra achar qualquer livro na hora.' },
      { image: 'leitura', title: 'Leitura estruturada, sessão por sessão', desc: 'Cada sessão traz contexto histórico, mapa, curiosidades e espaço pra suas anotações — sem precisar sair do app pra entender o que está lendo.' },
      { image: 'estudos', title: 'Estudos aprofundados, além da leitura diária', desc: 'Estudos temáticos como o do Pentateuco trazem contexto histórico, geográfico e teológico completos, divididos em sessões de ~35 min com perguntas de reflexão.' },
      { image: 'oracao', title: 'Oração estruturada com o método ACTS', desc: 'Adoração, Confissão, Ação de Graças e Súplicas, com um temporizador que avança sozinho de etapa em etapa — um aviso sonoro toca na troca, pra sua oração ter direção sem virar rotina automática.' },
      { image: 'reflexao', title: 'Feche o dia com uma reflexão guiada', desc: 'Reviver, Entender e Aplicar — três etapas curtas com temporizador pra você parar e pensar no que Deus falou com você na leitura de hoje, antes de seguir com o dia.' },
      { image: 'progresso', title: 'Veja seu crescimento espiritual', desc: 'Estatísticas por livro, por bloco e da Bíblia inteira, além de níveis e conquistas que te mantêm motivado dia após dia.' },
      { image: 'grupos', title: 'Sua Comunidade: amigos, grupos e desafios', desc: 'Adicione amigos, crie grupos de leitura e proponha desafios com nome e descrição próprios, como "Maratona de Marcos" — o moderador do grupo decide quando encerrar. Veja quantos amigos cada pessoa tem e adicione amigos em comum direto do perfil dela.' },
      { image: 'perfil', title: 'Seu perfil, do seu jeito', desc: 'Escolha uma foto, escreva uma mensagem e decida se quer compartilhar seu progresso com os amigos ou manter tudo privado — só nome, foto e mensagem ficam visíveis por padrão. Você muda de ideia quando quiser.' },
    ],
    featuresTitle: 'Tudo o que você precisa pra ler a Bíblia com constância',
    featuresSubtitle: 'Sem complicação, sem culpa — só um passo de cada vez.',
    features: [
      { icon: 'Flame', title: 'Rotina diária com Deus', desc: 'Oração, leitura e reflexão — três passos simples todo dia, com uma sequência que só conta quando os três são feitos, e um calendário do seu histórico.' },
      { icon: 'BookOpen', title: 'Planos de leitura flexíveis', desc: 'Leve, Padrão, Intensivo ou Livre (sem tempo definido) — escolha o ritmo que cabe na sua rotina, troque quando quiser, e use a busca pra achar qualquer livro na hora.' },
      { icon: 'HandHeart', title: 'Oração guiada (ACTS)', desc: 'Adoração, Confissão, Gratidão e Súplica, com um temporizador que avança sozinho de etapa em etapa e avisa com um som na troca.' },
      { icon: 'PenLine', title: 'Reflexão guiada', desc: 'Termine sua leitura com um roteiro guiado em 3 etapas — Reviver, Entender e Aplicar — com temporizador, pra fechar o dia com o que Deus falou com você.' },
      { icon: 'Compass', title: 'Jornada por blocos', desc: 'Pentateuco, Históricos, Poéticos, Profetas e mais — organizados por Antigo e Novo Testamento, com progresso visual de cada um.' },
      { icon: 'GraduationCap', title: 'Estudos aprofundados', desc: 'Estudos temáticos (como o do Pentateuco) com contexto histórico, geográfico e teológico, em sessões curtas com perguntas de reflexão.' },
      { icon: 'BarChart3', title: 'Acompanhamento de progresso', desc: 'Estatísticas por livro, por bloco e no total da Bíblia, sempre atualizadas.' },
      { icon: 'Award', title: 'Conquistas e níveis', desc: 'Desbloqueie medalhas e suba de nível conforme avança na leitura e na oração.' },
      { icon: 'Globe', title: 'Português e inglês', desc: 'Todo o conteúdo bilíngue, incluindo curiosidades e contexto histórico de cada livro.' },
      { icon: 'Users', title: 'Comunidade: amigos, grupos e desafios', desc: 'Convide amigos, crie grupos, proponha desafios nomeados com descrição própria e veja quantos amigos cada pessoa tem — tudo com um feed de atualizações e privacidade no seu controle.' },
      { icon: 'User', title: 'Perfil personalizável e privado', desc: 'Foto, mensagem e nome editáveis a qualquer momento. Você decide se compartilha seu progresso com os amigos ou mantém tudo privado.' },
    ],
    pricingTitle: 'Um plano só, sem letra miúda.',
    pricingSubtitle: 'Mensal ou anual — você escolhe. Sem anúncios.',
    pricingMemberItems: [
      'Todos os planos de leitura',
      'Oração guiada com temporizador',
      'Estudos aprofundados',
      'Progresso, conquistas e níveis',
      'Conteúdo em português e inglês',
    ],
    pricingMonthlyTitle: 'Mensal',
    pricingMonthlyPrice: 'R$ 19,90',
    pricingMonthlyPeriod: '/mês',
    pricingAnnualTitle: 'Anual',
    pricingAnnualBadge: 'Com desconto',
    pricingAnnualPrice: 'R$ 159,90',
    pricingAnnualPeriod: '/ano',
    pricingAnnualNote: 'Equivale a R$ 13,33/mês',
    pricingCta: 'Assinar',
    downloadTitle: 'Baixe onde quiser',
    downloadSubtitle: 'Já disponível na web. Play Store e App Store em breve.',
    downloadWebTitle: 'Web App',
    downloadWebDesc: 'Funciona agora, direto do navegador',
    downloadPlayTitle: 'Google Play',
    downloadAppleTitle: 'App Store',
    comingSoon: 'Em breve',
    faqTitle: 'Perguntas frequentes',
    faq: [
      { q: 'Preciso pagar pra usar o Jesus\' Corner?', a: 'Ainda não — a assinatura (mensal R$19,90 ou anual com desconto R$159,90) está em preparação e vai liberar acesso completo a todos os recursos. Por enquanto, o app já está disponível gratuitamente com planos de leitura, oração guiada, estudos, progresso e conquistas.' },
      { q: 'Funciona sem internet?', a: 'Sim. Como é um Web App instalável (PWA), o conteúdo já visitado fica salvo no seu dispositivo e funciona offline.' },
      { q: 'Em quais idiomas o app está disponível?', a: 'Português e inglês, com troca de idioma a qualquer momento direto no seu perfil.' },
      { q: 'Qual versão da Bíblia o app usa?', a: 'Hoje o texto bíblico completo já está disponível no app em duas versões de domínio público: World English Bible (inglês) e Almeida 1911 (português). Mais versões serão adicionadas em breve.' },
      { q: 'Vai ter versão nativa na Play Store e App Store?', a: 'Sim, estão em preparação. Enquanto isso, você já pode instalar o Web App na tela inicial do seu celular e usar como um app normal.' },
      { q: 'Meus amigos veem meu progresso de leitura?', a: 'Só se você quiser. Por padrão seu perfil é privado — amigos veem seu nome, foto e mensagem, mas nada do seu progresso. Você pode deixar o perfil público a qualquer momento pra compartilhar seu progresso geral, o que está lendo e seus grupos.' },
      { q: 'Tem restrição de idade pra usar a Comunidade?', a: 'Sim — a Comunidade (amigos, grupos e desafios) é liberada só a partir de 16 anos, com base na data de nascimento informada no cadastro. O resto do app não tem essa restrição.' },
    ],
    contactTitle: 'Fale conosco',
    contactSubtitle: 'Dúvidas, sugestões ou algo não funcionando como devia? Escreva pra gente abaixo.',
    contactNameLabel: 'Nome',
    contactNamePlaceholder: 'Seu nome',
    contactEmailLabel: 'E-mail',
    contactEmailPlaceholder: 'seu@email.com',
    contactMessageLabel: 'Mensagem',
    contactMessagePlaceholder: 'Escreva sua mensagem...',
    contactRequiredError: 'Preencha nome, e-mail e mensagem antes de enviar.',
    contactSubmitBtn: 'Enviar mensagem',
    contactSending: 'Enviando...',
    contactSuccessTitle: 'Mensagem enviada!',
    contactSuccessSub: 'Obrigado por escrever — vamos responder no e-mail que você deixou assim que possível.',
    contactSendAnother: 'Enviar outra mensagem',
    footerTagline: 'Feito com fé, um capítulo de cada vez.',
    footerPrivacyLink: 'Política de Privacidade',
    footerTermsLink: 'Termos de Uso',
    footerRights: 'Todos os direitos reservados.',
  },
  en: {
    navFeatures: 'Features',
    navPricing: 'Pricing',
    navFaq: 'FAQ',
    navContact: 'Contact',
    navCta: 'Sign in',
    navOpenMenu: 'Open menu',
    navCloseMenu: 'Close menu',
    heroBadge: 'Available now as a Web App',
    heroTitle: 'Your time. Your routine. Your connection with God.',
    heroSubtitle: 'Quality time, just for you, with God and the Bible — no rush, no distractions. Structured prayer and reading, every day, as part of your routine.',
    heroCtaPrimary: 'Get started',
    heroCtaSecondary: 'See features',
    heroNote: 'Works right in your browser, no install needed. Coming soon to the Play Store and App Store.',
    mockSessionLabel: "TODAY'S SESSION",
    aboutNameEyebrow: 'Where the name comes from',
    aboutNameTitle: 'Why "Jesus\' Corner"?',
    aboutNameVerseText: 'But when you pray, go into your room, close the door and pray to your Father, who is unseen. Then your Father, who sees what is done in secret, will reward you.',
    aboutNameVerseRef: 'Matthew 6:6 · NIV',
    aboutNameBody: "The name comes from that \"room\": a corner that's just yours, no audience, no comparison — just you, the Bible, and God. It's not about grand religious gestures, it's about creating that space every day, in your own time, for quality time that's yours alone.",
    showcaseEyebrow: 'Straight from the app',
    showcase: [
      { image: 'home', title: 'Your routine with God, every day', desc: 'Three simple steps — prayer, reading, and reflection — right on your home screen. Your streak only counts when you complete all three, and a calendar shows your full history.' },
      { image: 'rotina', title: 'Set up your routine, your way', desc: 'Choose how long prayer and reflection take, see your total time for the day, and track the 3 steps on a timeline that fills in as you go — with a button to jump straight into prayer.' },
      { image: 'jornada', title: 'Your journey, organized by Old and New Testament', desc: 'Every block of the Bible — Pentateuch, Historical Books, Prophets, and more — shows the books that make it up: tap a book to jump straight into reading it. Not sure where to look? Use search to find any book instantly.' },
      { image: 'leitura', title: 'Structured reading, session by session', desc: 'Every session comes with historical context, a map, trivia, and space for your own notes — no need to leave the app to understand what you\'re reading.' },
      { image: 'estudos', title: 'In-depth studies, beyond the daily reading', desc: 'Thematic studies like the Pentateuch one bring complete historical, geographical, and theological context, split into ~35-min sessions with reflection questions.' },
      { image: 'oracao', title: 'Structured prayer with the ACTS method', desc: 'Adoration, Confession, Thanksgiving, and Supplication, with a timer that moves through each step on its own — a sound plays at each transition, so your prayer has direction without becoming an empty routine.' },
      { image: 'reflexao', title: 'Close the day with a guided reflection', desc: 'Recall, Understand, and Apply — three short steps with a timer, so you pause and think about what God spoke to you in today\'s reading before moving on with your day.' },
      { image: 'progresso', title: 'See your spiritual growth', desc: 'Stats by book, by block, and across the whole Bible, plus levels and achievements that keep you motivated day after day.' },
      { image: 'grupos', title: 'Your Community: friends, groups, and challenges', desc: 'Add friends, create reading groups, and propose named challenges with their own description, like "Mark Marathon" — the group moderator decides when to close it. See how many friends each person has and add mutual friends straight from their profile.' },
      { image: 'perfil', title: 'Your profile, your way', desc: "Pick a photo, write a bio, and decide whether to share your progress with friends or keep everything private — only your name, photo, and bio are visible by default. Change your mind anytime." },
    ],
    featuresTitle: 'Everything you need to read the Bible consistently',
    featuresSubtitle: 'No complications, no guilt — just one step at a time.',
    features: [
      { icon: 'Flame', title: 'Daily routine with God', desc: 'Prayer, reading, and reflection — three simple steps every day, with a streak that only counts when all three are done, and a calendar of your history.' },
      { icon: 'BookOpen', title: 'Flexible reading plans', desc: 'Light, Standard, Intensive, or Free (no time target) — pick the pace that fits your routine, switch anytime, and use search to find any book instantly.' },
      { icon: 'HandHeart', title: 'Guided prayer (ACTS)', desc: 'Adoration, Confession, Thanksgiving, and Supplication, with a timer that moves through each step on its own and plays a sound at each transition.' },
      { icon: 'PenLine', title: 'Guided reflection', desc: 'Wrap up your reading with a guided 3-step routine — Recall, Understand, and Apply — with a timer, to close the day with what God spoke to you.' },
      { icon: 'Compass', title: 'Journey through blocks', desc: 'Pentateuch, Historical, Poetic, Prophets, and more — organized by Old and New Testament, with visual progress for each one.' },
      { icon: 'GraduationCap', title: 'In-depth studies', desc: 'Thematic studies (like the Pentateuch one) with historical, geographical, and theological context, in short sessions with reflection questions.' },
      { icon: 'BarChart3', title: 'Progress tracking', desc: 'Stats by book, by block, and across the whole Bible, always up to date.' },
      { icon: 'Award', title: 'Achievements and levels', desc: 'Unlock badges and level up as you progress through reading and prayer.' },
      { icon: 'Globe', title: 'Portuguese and English', desc: 'All content available in both languages, including trivia and historical context for each book.' },
      { icon: 'Users', title: 'Community: friends, groups, and challenges', desc: 'Invite friends, create groups, propose named challenges with their own description, and see how many friends each person has — all with an updates feed and privacy on your terms.' },
      { icon: 'User', title: 'Customizable, private profile', desc: 'Photo, bio, and name, editable anytime. You decide whether to share your progress with friends or keep everything private.' },
    ],
    pricingTitle: 'One plan, no fine print.',
    pricingSubtitle: 'Monthly or annual — you choose. No ads.',
    pricingMemberItems: [
      'All reading plans',
      'Guided prayer with timer',
      'In-depth studies',
      'Progress, achievements, and levels',
      'Content in Portuguese and English',
    ],
    pricingMonthlyTitle: 'Monthly',
    pricingMonthlyPrice: '$9.90',
    pricingMonthlyPeriod: '/month',
    pricingAnnualTitle: 'Annual',
    pricingAnnualBadge: 'Discounted',
    pricingAnnualPrice: '$79.90',
    pricingAnnualPeriod: '/year',
    pricingAnnualNote: 'Equivalent to $6.66/month',
    pricingCta: 'Subscribe',
    downloadTitle: 'Get it anywhere',
    downloadSubtitle: 'Already available on the web. Play Store and App Store coming soon.',
    downloadWebTitle: 'Web App',
    downloadWebDesc: 'Works right now, straight from your browser',
    downloadPlayTitle: 'Google Play',
    downloadAppleTitle: 'App Store',
    comingSoon: 'Coming soon',
    faqTitle: 'Frequently asked questions',
    faq: [
      { q: 'Do I need to pay to use Jesus\' Corner?', a: 'Not yet — the subscription (monthly $9.90 or discounted annual $79.90) is in the works and will unlock full access to every feature. For now, the app is already free to use, with reading plans, guided prayer, studies, progress, and achievements.' },
      { q: 'Does it work without internet?', a: 'Yes. As an installable Web App (PWA), content you\'ve already visited is saved on your device and works offline.' },
      { q: 'What languages is the app available in?', a: 'Portuguese and English, switchable anytime right from your profile.' },
      { q: 'Which Bible version does the app use?', a: 'The full Bible text is already available in the app in two public-domain versions: World English Bible (English) and Almeida 1911 (Portuguese). More versions will be added soon.' },
      { q: 'Will there be a native version on the Play Store and App Store?', a: 'Yes, it\'s in the works. In the meantime, you can already install the Web App on your home screen and use it like a regular app.' },
      { q: 'Can my friends see my reading progress?', a: "Only if you want them to. By default your profile is private — friends see your name, photo, and bio, but none of your progress. You can make your profile public anytime to share your overall progress, what you're reading, and your groups." },
      { q: 'Is there an age requirement for the Community?', a: "Yes — the Community (friends, groups, and challenges) is only available from age 16, based on the date of birth entered at signup. The rest of the app has no such restriction." },
    ],
    contactTitle: 'Contact us',
    contactSubtitle: "Questions, suggestions, or something not working right? Write to us below.",
    contactNameLabel: 'Name',
    contactNamePlaceholder: 'Your name',
    contactEmailLabel: 'Email',
    contactEmailPlaceholder: 'you@email.com',
    contactMessageLabel: 'Message',
    contactMessagePlaceholder: 'Write your message...',
    contactRequiredError: 'Fill in your name, email, and message before sending.',
    contactSubmitBtn: 'Send message',
    contactSending: 'Sending...',
    contactSuccessTitle: 'Message sent!',
    contactSuccessSub: "Thanks for writing — we'll reply to the email you left as soon as we can.",
    contactSendAnother: 'Send another message',
    footerTagline: 'Made in faith, one chapter at a time.',
    footerPrivacyLink: 'Privacy Policy',
    footerTermsLink: 'Terms of Use',
    footerRights: 'All rights reserved.',
  },
}
