export const content = {
  pt: {
    navFeatures: 'Recursos',
    navPricing: 'Planos',
    navFaq: 'Perguntas',
    navContact: 'Fale Conosco',
    navCta: 'Entrar',
    navOpenMenu: 'Abrir menu',
    navCloseMenu: 'Fechar menu',
    heroBadge: 'Disponível agora como Web App',
    heroTitle: 'Seu tempo. Sua rotina. Sua conexão com Deus.',
    heroSubtitle: 'Um tempo de qualidade, só seu, com Deus e a Bíblia — sem pressa, sem distração. Oração e leitura estruturadas, todo dia, como parte da sua rotina.',
    heroCtaPrimary: 'Começar agora',
    heroCtaSecondary: 'Ver recursos',
    heroNote: 'Funciona no navegador, sem instalação. Em breve na Play Store e App Store.',
    mockSessionLabel: 'SESSÃO DE HOJE',
    purposeEyebrow: 'Nosso propósito',
    purposeTitle: 'A história de amor mais bonita já contada.',
    purposeSubtitle: 'E ela é pra todo mundo.',
    purposeBody: 'A Bíblia conta a história de um Deus que ama, busca e nunca desiste do Seu povo — do Éden até a eternidade. O Jesus\' Corner existe pra te aproximar dessa história todos os dias, com uma plataforma completa pra acompanhar sua caminhada de leitura. E porque essa história é pra todo mundo, o valor da sua contribuição fica com você: pode ser R$0, mensal, anual, o que fizer sentido — o acesso completo nunca fica bloqueado por dinheiro.',
    aboutNameEyebrow: 'A origem do nome',
    aboutNameTitle: 'Por que "Jesus\' Corner"?',
    aboutNameVerseText: 'Mas, quando orarem, cada um vá para seu quarto, feche a porta e ore a seu Pai, em segredo. Então seu Pai, que observa em segredo, os recompensará.',
    aboutNameVerseRef: 'Mateus 6:6 · Nova Versão Transformadora (NVT)',
    aboutNameBody: 'O nome nasce desse "quarto": um cantinho só seu, sem plateia, sem comparação — só você, a Bíblia e Deus. Não é sobre grandes gestos religiosos, é sobre criar esse espaço todo dia, no seu tempo, pra um tempo de qualidade que é só seu.',
    ctaPurposeText: 'Comece hoje mesmo — o primeiro passo é só seu.',
    ctaPurposeBtn: 'Começar agora',
    ctaAboutNameText: 'Seu cantinho com Deus está a um clique de distância.',
    ctaAboutNameBtn: 'Criar meu cantinho',
    showcaseEyebrow: 'Direto do app',
    showcaseFeaturedTag: 'Em destaque',
    showcase: [
      { image: 'leitura', title: 'Leia a Bíblia inteira, capítulo por capítulo', desc: 'Cada capítulo traz o texto bíblico completo, com contexto histórico, mapa e curiosidades — numa coluna larga e confortável de ler. Termine e marque como lido sem sair da tela; um toque leva direto pro próximo capítulo.' },
      { image: 'rotina', title: 'Sua rotina com Deus, num só lugar', desc: 'Oração, leitura e reflexão organizadas numa linha do tempo que se preenche conforme você avança. Veja a sessão de leitura do dia, o tempo de cada passo, e comece por onde quiser — tudo na aba Rotina.' },
      { image: 'progresso', title: 'Acompanhe sua constância, semana a semana', desc: 'Um gráfico mostra quantos dias você orou, leu e refletiu nas últimas semanas, com a semana atual sempre em destaque — além de estatísticas por livro, por bloco, níveis e conquistas.' },
    ],
    ctaShowcaseText: 'Viu como funciona? Agora é sua vez de experimentar.',
    ctaShowcaseBtn: 'Quero começar',
    featuresTitle: 'Tudo o que você precisa pra ler a Bíblia com constância',
    featuresSubtitle: 'Sem complicação, sem culpa — só um passo de cada vez.',
    features: [
      { icon: 'Flame', title: 'Rotina diária com Deus', desc: 'Oração, leitura e reflexão — três passos simples todo dia, com uma sequência que só conta quando os três são feitos, e um calendário do seu histórico.' },
      { icon: 'BookOpen', title: 'Planos de leitura flexíveis', desc: 'Leve, Padrão, Intensivo ou Livre (sem tempo definido) — escolha o ritmo que cabe na sua rotina, troque quando quiser, e use a busca pra achar qualquer livro na hora.' },
      { icon: 'HandHeart', title: 'Oração guiada (ACTS)', desc: 'Adoração, Confissão, Gratidão e Súplica, com um temporizador que avança sozinho de etapa em etapa e avisa com um som na troca.' },
      { icon: 'PenLine', title: 'Reflexão guiada', desc: 'Termine sua leitura com um roteiro guiado em 3 etapas — Reviver, Entender e Aplicar — com temporizador, pra fechar o dia com o que Deus falou com você.' },
      { icon: 'Compass', title: 'Jornada por blocos', desc: 'Pentateuco, Históricos, Poéticos, Profetas e mais — organizados por Antigo e Novo Testamento, com progresso visual de cada um.' },
      { icon: 'GraduationCap', title: 'Estudos aprofundados', desc: 'Quatro estudos temáticos — Pentateuco, Cronologia da Bíblia, Salmos e As Alianças de Deus — com contexto histórico, geográfico e teológico, 43 sessões com perguntas de reflexão.' },
      { icon: 'BarChart3', title: 'Acompanhamento de progresso', desc: 'Estatísticas por livro, por bloco e no total da Bíblia, gráfico de constância da rotina, sempre atualizados.' },
      { icon: 'Award', title: 'Conquistas e níveis', desc: 'Desbloqueie medalhas e suba de nível conforme avança na leitura e na oração, com um mural completo de conquistas.' },
      { icon: 'Globe', title: 'Português e inglês', desc: 'Todo o conteúdo bilíngue, incluindo curiosidades e contexto histórico de cada livro.' },
      { icon: 'Users', title: 'Comunidade: amigos, grupos e desafios', desc: 'Convide amigos, crie grupos, proponha desafios nomeados com descrição própria e veja quantos amigos cada pessoa tem — tudo com um feed de atualizações e privacidade no seu controle.' },
      { icon: 'User', title: 'Perfil personalizável e privado', desc: 'Foto, mensagem e nome editáveis a qualquer momento. Você decide se compartilha seu progresso com os amigos ou mantém tudo privado.' },
    ],
    ctaFeaturesText: 'Tudo isso, sem custo nenhum pra começar.',
    ctaFeaturesBtn: 'Começar de graça',
    pricingTitle: 'Você decide quanto vale pra você.',
    pricingSubtitle: 'Sem anúncios, sem versão limitada — sempre acesso ao app inteiro.',
    pricingBody: 'O Jesus\' Corner existe pra incentivar uma rotina diária com Deus. Quanto contribuir fica a seu critério — mensal ou anual, de R$0 até o valor que achar justo — e você pode mudar isso quando quiser dentro do app. Cada contribuição ajuda o Jesus\' Corner a ficar cada vez mais acessível.',
    pricingMemberItems: [
      'Leitura diária com planos flexíveis e texto bíblico completo',
      'Contexto histórico dos 66 livros da Bíblia, capítulo por capítulo',
      'Oração guiada (ACTS) e reflexão guiada',
      '4 estudos aprofundados — Pentateuco, Cronologia, Salmos e Alianças (43 sessões)',
      'Comunidade: amigos, grupos e desafios',
      'Estatísticas completas e mural de conquistas',
      'Notas ilimitadas',
    ],
    pricingCta: 'Escolher meu valor',
    downloadTitle: 'Baixe onde quiser',
    downloadSubtitle: 'Já disponível na web. Play Store e App Store em breve.',
    downloadWebTitle: 'Web App',
    downloadWebDesc: 'Instale direto do navegador',
    downloadPlayTitle: 'Google Play',
    downloadAppleTitle: 'App Store',
    comingSoon: 'Em breve',
    installTitle: 'Instale o Jesus\' Corner no seu celular',
    installSubtitle: 'Sem loja de aplicativos, sem espaço extra no celular — funciona direto do navegador, com ícone na tela inicial como qualquer outro app.',
    installIosTitle: 'No iPhone (Safari)',
    installIosSteps: [
      'Abra jesuscorner.app no Safari — precisa ser o Safari, outros navegadores do iPhone não mostram essa opção.',
      'Toque no ícone de compartilhar (o quadrado com uma seta pra cima), na barra de baixo.',
      'Role a lista de opções e toque em "Adicionar à Tela de Início".',
      'Toque em "Adicionar", no canto superior direito.',
    ],
    installAndroidTitle: 'No Android (Chrome)',
    installAndroidSteps: [
      'Abra jesuscorner.app no Chrome.',
      'Toque nos três pontinhos, no canto superior direito.',
      'Toque em "Adicionar à tela inicial" (ou "Instalar app", se aparecer).',
      'Confirme tocando em "Adicionar" ou "Instalar".',
    ],
    installCta: 'Abrir o Jesus\' Corner',
    faqTitle: 'Perguntas frequentes',
    faq: [
      { q: 'Preciso pagar pra usar o Jesus\' Corner?', a: 'Não precisa. Você escolhe quanto contribuir — mensal ou anual, e pode ser R$0. Contribuir com um valor maior ajuda o Jesus\' Corner a continuar existindo e chegando a mais gente, mas o acesso completo — leitura diária em todos os planos, oração guiada, os 4 estudos aprofundados, reflexão guiada, contexto histórico dos 66 livros da Bíblia, Comunidade (amigos, grupos e desafios), estatísticas completas e notas ilimitadas — nunca fica bloqueado por dinheiro.' },
      { q: 'Funciona sem internet?', a: 'Sim. Como é um Web App instalável (PWA), o conteúdo já visitado fica salvo no seu dispositivo e funciona offline.' },
      { q: 'Em quais idiomas o app está disponível?', a: 'Português e inglês, com troca de idioma a qualquer momento direto no seu perfil.' },
      { q: 'Qual versão da Bíblia o app usa?', a: 'Hoje o texto bíblico completo já está disponível no app em duas versões licenciadas via API.Bible: Nova Versão Transformadora — NVT (português) e New Living Translation — NLT (inglês). Mais versões serão adicionadas em breve.' },
      { q: 'Vai ter versão nativa na Play Store e App Store?', a: 'Sim, estão em preparação. Enquanto isso, você já pode instalar o Web App na tela inicial do seu celular e usar como um app normal.' },
      { q: 'Meus amigos veem meu progresso de leitura?', a: 'Por padrão, sim — seu perfil já nasce público pros seus amigos, que veem seu progresso geral de leitura, o que você está lendo e seus grupos, além de nome, foto e mensagem. Se preferir mais privacidade, você pode deixar o perfil privado a qualquer momento em Perfil — aí só nome, foto e mensagem continuam visíveis.' },
      { q: 'Tem restrição de idade pra usar a Comunidade?', a: 'Sim — a Comunidade (amigos, grupos e desafios) é liberada só a partir de 16 anos, com base na data de nascimento informada no cadastro. O resto do app não tem essa restrição.' },
    ],
    ctaFaqText: 'Ainda com dúvidas? A melhor forma de saber é experimentando.',
    ctaFaqBtn: 'Experimentar agora',
    contactTitle: 'Fale conosco',
    contactSubtitle: 'Dúvidas, sugestões ou algo não funcionando como devia? Escreva pra gente abaixo.',
    contactNameLabel: 'Nome',
    contactNamePlaceholder: 'Seu nome',
    contactEmailLabel: 'E-mail',
    contactEmailPlaceholder: 'seu@email.com',
    contactMessageLabel: 'Mensagem',
    contactMessagePlaceholder: 'Escreva sua mensagem...',
    contactRequiredError: 'Preencha nome, e-mail e mensagem antes de enviar.',
    contactSubmitBtn: 'Enviar mensagem',
    contactSending: 'Enviando...',
    contactSuccessTitle: 'Mensagem enviada!',
    contactSuccessSub: 'Obrigado por escrever — vamos responder no e-mail que você deixou assim que possível.',
    contactSendAnother: 'Enviar outra mensagem',
    footerTagline: 'Feito com fé, um capítulo de cada vez.',
    footerInstagramLabel: 'Instagram do Jesus\' Corner',
    footerPrivacyLink: 'Política de Privacidade',
    footerTermsLink: 'Termos de Uso',
    footerRights: 'Todos os direitos reservados.',
  },
  en: {
    navFeatures: 'Features',
    navPricing: 'Pricing',
    navFaq: 'FAQ',
    navContact: 'Contact',
    navCta: 'Sign in',
    navOpenMenu: 'Open menu',
    navCloseMenu: 'Close menu',
    heroBadge: 'Available now as a Web App',
    heroTitle: 'Your time. Your routine. Your connection with God.',
    heroSubtitle: 'Quality time, just for you, with God and the Bible — no rush, no distractions. Structured prayer and reading, every day, as part of your routine.',
    heroCtaPrimary: 'Get started',
    heroCtaSecondary: 'See features',
    heroNote: 'Works right in your browser, no install needed. Coming soon to the Play Store and App Store.',
    mockSessionLabel: "TODAY'S SESSION",
    purposeEyebrow: 'Our purpose',
    purposeTitle: "The most beautiful love story ever told.",
    purposeSubtitle: "And it's for everyone.",
    purposeBody: "The Bible tells the story of a God who loves, pursues, and never gives up on His people — from Eden to eternity. Jesus' Corner exists to bring you closer to that story every day, with a complete platform to track your reading journey. And because that story is for everyone, how much you contribute is up to you: it can be $0, monthly, annual, whatever makes sense for you — full access is never locked behind money.",
    aboutNameEyebrow: 'Where the name comes from',
    aboutNameTitle: 'Why "Jesus\' Corner"?',
    aboutNameVerseText: 'But when you pray, go away by yourself, shut the door behind you, and pray to your Father in private. Then your Father, who sees everything, will reward you.',
    aboutNameVerseRef: 'Matthew 6:6 · New Living Translation (NLT)',
    aboutNameBody: "The name comes from that \"room\": a corner that's just yours, no audience, no comparison — just you, the Bible, and God. It's not about grand religious gestures, it's about creating that space every day, in your own time, for quality time that's yours alone.",
    ctaPurposeText: 'Start today — the first step is yours to take.',
    ctaPurposeBtn: 'Get started',
    ctaAboutNameText: 'Your corner with God is just one click away.',
    ctaAboutNameBtn: 'Create my corner',
    showcaseEyebrow: 'Straight from the app',
    showcaseFeaturedTag: 'Featured',
    showcase: [
      { image: 'leitura', title: 'Read the whole Bible, chapter by chapter', desc: 'Every chapter brings the full Bible text, with historical context, a map, and trivia — in a wide, comfortable reading column. Finish and mark it as read without leaving the screen; one tap takes you straight to the next chapter.' },
      { image: 'rotina', title: 'Your routine with God, in one place', desc: "Prayer, reading, and reflection laid out on a timeline that fills in as you go. See today's reading session, how long each step takes, and start wherever you like — all from the Routine tab." },
      { image: 'progresso', title: 'Track your consistency, week by week', desc: 'A chart shows how many days you prayed, read, and reflected over the past few weeks, with the current week always highlighted — plus stats by book, by block, levels, and achievements.' },
    ],
    ctaShowcaseText: 'See how it works? Now it\'s your turn to try it.',
    ctaShowcaseBtn: 'I want to start',
    featuresTitle: 'Everything you need to read the Bible consistently',
    featuresSubtitle: 'No complications, no guilt — just one step at a time.',
    features: [
      { icon: 'Flame', title: 'Daily routine with God', desc: 'Prayer, reading, and reflection — three simple steps every day, with a streak that only counts when all three are done, and a calendar of your history.' },
      { icon: 'BookOpen', title: 'Flexible reading plans', desc: 'Light, Standard, Intensive, or Free (no time target) — pick the pace that fits your routine, switch anytime, and use search to find any book instantly.' },
      { icon: 'HandHeart', title: 'Guided prayer (ACTS)', desc: 'Adoration, Confession, Thanksgiving, and Supplication, with a timer that moves through each step on its own and plays a sound at each transition.' },
      { icon: 'PenLine', title: 'Guided reflection', desc: 'Wrap up your reading with a guided 3-step routine — Recall, Understand, and Apply — with a timer, to close the day with what God spoke to you.' },
      { icon: 'Compass', title: 'Journey through blocks', desc: 'Pentateuch, Historical, Poetic, Prophets, and more — organized by Old and New Testament, with visual progress for each one.' },
      { icon: 'GraduationCap', title: 'In-depth studies', desc: 'Four thematic studies — Pentateuch, Bible Chronology, Psalms, and The Covenants of God — with historical, geographical, and theological context, 43 sessions with reflection questions.' },
      { icon: 'BarChart3', title: 'Progress tracking', desc: 'Stats by book, by block, and across the whole Bible, a routine consistency chart, always up to date.' },
      { icon: 'Award', title: 'Achievements and levels', desc: 'Unlock badges and level up as you progress through reading and prayer, with a full achievements board.' },
      { icon: 'Globe', title: 'Portuguese and English', desc: 'All content available in both languages, including trivia and historical context for each book.' },
      { icon: 'Users', title: 'Community: friends, groups, and challenges', desc: 'Invite friends, create groups, propose named challenges with their own description, and see how many friends each person has — all with an updates feed and privacy on your terms.' },
      { icon: 'User', title: 'Customizable, private profile', desc: 'Photo, bio, and name, editable anytime. You decide whether to share your progress with friends or keep everything private.' },
    ],
    ctaFeaturesText: 'All of this, with no cost to get started.',
    ctaFeaturesBtn: 'Start for free',
    pricingTitle: 'You decide what it\'s worth to you.',
    pricingSubtitle: 'No ads, no limited version — always full access to the whole app.',
    pricingBody: "Jesus' Corner exists to encourage a daily routine with God. How much you contribute is entirely up to you — monthly or annual, from $0 up to whatever feels right — and you can change it anytime inside the app. Every contribution helps make Jesus' Corner more and more accessible.",
    pricingMemberItems: [
      'Daily reading with flexible plans and the full Bible text',
      'Historical context for all 66 books of the Bible, chapter by chapter',
      'Guided prayer (ACTS) and guided reflection',
      '4 in-depth studies — Pentateuch, Chronology, Psalms, and Covenants (43 sessions)',
      'Community: friends, groups, and challenges',
      'Complete stats and achievements board',
      'Unlimited notes',
    ],
    pricingCta: 'Choose my amount',
    downloadTitle: 'Get it anywhere',
    downloadSubtitle: 'Already available on the web. Play Store and App Store coming soon.',
    downloadWebTitle: 'Web App',
    downloadWebDesc: 'Install right from your browser',
    downloadPlayTitle: 'Google Play',
    downloadAppleTitle: 'App Store',
    comingSoon: 'Coming soon',
    installTitle: 'Install Jesus\' Corner on your phone',
    installSubtitle: 'No app store, no extra space on your phone — it works straight from your browser, with an icon on your home screen just like any other app.',
    installIosTitle: 'On iPhone (Safari)',
    installIosSteps: [
      'Open jesuscorner.app in Safari — it has to be Safari, other iPhone browsers don\'t show this option.',
      'Tap the share icon (the square with an arrow pointing up) in the bottom bar.',
      'Scroll the list of options and tap "Add to Home Screen".',
      'Tap "Add" in the top-right corner.',
    ],
    installAndroidTitle: 'On Android (Chrome)',
    installAndroidSteps: [
      'Open jesuscorner.app in Chrome.',
      'Tap the three dots in the top-right corner.',
      'Tap "Add to Home screen" (or "Install app", if that shows up instead).',
      'Confirm by tapping "Add" or "Install".',
    ],
    installCta: "Open Jesus' Corner",
    faqTitle: 'Frequently asked questions',
    faq: [
      { q: 'Do I need to pay to use Jesus\' Corner?', a: "No, you don't. You choose how much to contribute — monthly or annual, and it can be $0. Contributing more helps Jesus' Corner keep going and reach more people, but full access — daily reading on every plan, guided prayer, the 4 in-depth studies, guided reflection, historical context for all 66 books of the Bible, Community (friends, groups, and challenges), complete stats, and unlimited notes — is never locked behind payment." },
      { q: 'Does it work without internet?', a: 'Yes. As an installable Web App (PWA), content you\'ve already visited is saved on your device and works offline.' },
      { q: 'What languages is the app available in?', a: 'Portuguese and English, switchable anytime right from your profile.' },
      { q: 'Which Bible version does the app use?', a: 'The full Bible text is already available in the app in two versions licensed through API.Bible: New Living Translation — NLT (English) and Nova Versão Transformadora — NVT (Portuguese). More versions will be added soon.' },
      { q: 'Will there be a native version on the Play Store and App Store?', a: 'Yes, it\'s in the works. In the meantime, you can already install the Web App on your home screen and use it like a regular app.' },
      { q: 'Can my friends see my reading progress?', a: "By default, yes — your profile starts out public to friends, who can see your overall reading progress, what you're currently reading, and your groups, plus your name, photo, and bio. If you'd rather keep it private, you can switch that off anytime in Profile — only your name, photo, and bio stay visible after that." },
      { q: 'Is there an age requirement for the Community?', a: "Yes — the Community (friends, groups, and challenges) is only available from age 16, based on the date of birth entered at signup. The rest of the app has no such restriction." },
    ],
    ctaFaqText: 'Still have questions? The best way to find out is to try it.',
    ctaFaqBtn: 'Try it now',
    contactTitle: 'Contact us',
    contactSubtitle: "Questions, suggestions, or something not working right? Write to us below.",
    contactNameLabel: 'Name',
    contactNamePlaceholder: 'Your name',
    contactEmailLabel: 'Email',
    contactEmailPlaceholder: 'you@email.com',
    contactMessageLabel: 'Message',
    contactMessagePlaceholder: 'Write your message...',
    contactRequiredError: 'Fill in your name, email, and message before sending.',
    contactSubmitBtn: 'Send message',
    contactSending: 'Sending...',
    contactSuccessTitle: 'Message sent!',
    contactSuccessSub: "Thanks for writing — we'll reply to the email you left as soon as we can.",
    contactSendAnother: 'Send another message',
    footerTagline: 'Made in faith, one chapter at a time.',
    footerInstagramLabel: "Jesus' Corner on Instagram",
    footerPrivacyLink: 'Privacy Policy',
    footerTermsLink: 'Terms of Use',
    footerRights: 'All rights reserved.',
  },
}
