// Conteúdo da Política de Privacidade — texto legal, mantido separado de
// content.js (textos de marketing) por ser mais longo e menos frequentemente
// editado. Uma única fonte da verdade: o app apenas linka pra essa página no
// site, em vez de duplicar o texto nas duas plataformas.

export const privacyContent = {
  pt: {
    title: 'Política de Privacidade',
    updated: 'Última atualização: setembro de 2026',
    intro: 'Esta política explica quais dados o Jesus\' Corner coleta, como eles são usados e guardados, e quais são os seus direitos. Escrevemos em linguagem simples — sem juridiquês desnecessário — porque acreditamos que privacidade só funciona quando é compreensível.',
    sections: [
      {
        heading: '1. Quem somos',
        body: 'O Jesus\' Corner é operado pela JCORNER DESENVOLVIMENTO DE SOFTWARE LTDA, CNPJ 68.029.736/0001-26. A Encarregada pelo Tratamento de Dados Pessoais (DPO), conforme o art. 41 da LGPD, é Daniela Ziller, que pode ser contatada pelo e-mail info@jesuscorner.app. Para qualquer dúvida sobre privacidade ou pra exercer seus direitos como titular de dados, use esse mesmo contato.',
      },
      {
        heading: '2. Quais dados coletamos',
        body: 'Para criar uma conta, pedimos seu nome, e-mail, idade e uma senha forte (mínimo 8 caracteres, com letra maiúscula, minúscula, número e caractere especial) — a idade é usada só pra confirmar que você tem pelo menos 18 anos (o Jesus\' Corner é destinado a maiores de 18 — ver seção 12) e não é compartilhada com outros usuários. Se você assinar um dos planos pagos, também guardamos o status da sua assinatura (ativa, cancelada, o nível — Premium ou Premium + IA —, a periodicidade e a moeda escolhidas, e até quando ela vale) — ver seção 13 pra detalhes de pagamento. Conforme você usa o app, também são registrados: seu progresso de leitura (capítulos e reflexões concluídos), sequência de dias de uso, plano de leitura escolhido, idioma preferido, pedidos de oração, e o conteúdo que você escrever — anotações de leitura, reflexões diárias, frases de aplicação, marcações/grifos de versículos específicos (com nota opcional) e anotações de sermão (preletor, igreja e os textos bíblicos citados, quando você preencher) —, estatísticas de oração (quantos pedidos, quantas orações cronometradas) e progresso nos estudos temáticos e guiados. Você também pode, de forma totalmente opcional, adicionar uma mensagem curta ao seu perfil (sua foto de perfil, quando não configurada, mostra as iniciais do seu nome — não é possível enviar uma foto própria). Se você ativar lembretes de leitura por notificação push, guardamos os dados técnicos necessários pra isso (endereço do dispositivo/navegador junto ao serviço de notificações, fuso horário, e o horário/dias que você escolher). Se você usar os recursos sociais do app (a aba Comunidade), também registramos pedidos de amizade (enviados e recebidos), os grupos de leitura dos quais você participa, os desafios propostos nesses grupos, os comentários que você postar no mural de cada grupo, e um pequeno histórico com data/hora de marcos como livros concluídos, subidas de nível e entradas em grupos — ver seção 8 para saber quem consegue ver esses dados. Também registramos, de forma interna, em que passo do cadastro guiado cada pessoa está durante o processo de criar conta — usado só pra entender em que ponto as pessoas desistem e melhorar esse fluxo, nunca compartilhado com terceiros nem usado pra publicidade.',
      },
      {
        heading: '3. Recursos com Inteligência Artificial (IA)',
        body: 'Alguns recursos do Jesus\' Corner usam um modelo de IA pra gerar conteúdo ou responder perguntas: montar um plano de leitura ou um estudo a partir de um tema que você escreve, responder perguntas sobre o texto bíblico durante a leitura (chat com IA), buscar suas próprias anotações por assunto em vez de palavra exata, montar o resumo do seu boletim semanal a partir das anotações que você escreveu naquela semana, e converter o texto bíblico em voz alta (leitura em áudio e modo mãos-livres). Pra cada um desses recursos, só a informação necessária pra aquele pedido específico é enviada — o tema digitado, a pergunta feita, o texto das anotações relevantes, ou apenas o trecho da Bíblia a ser narrado, conforme o caso — através do Vercel AI Gateway, que roteia a requisição para os provedores de modelos de IA usados no momento: a Anthropic (modelos Claude) para os recursos de texto, e a OpenAI para a conversão de texto em voz. No caso da narração em áudio, o que é enviado é apenas o próprio texto bíblico do capítulo — nenhum dado pessoal, nenhuma anotação sua. Essa informação é usada só pra gerar aquela resposta específica, não é usada pra treinar modelos de terceiros e não é combinada com outros dados seus para fins de publicidade. Como medida de segurança, se uma pergunta feita ao chat sobre o texto sugerir risco de automutilação ou suicídio, o app sempre mostra, junto da resposta, o contato do CVV (Centro de Valorização da Vida) — independente do que a IA responder.',
      },
      {
        heading: '4. E-mails e notificações',
        body: 'Usamos a Resend Inc. para enviar os e-mails do Jesus\' Corner — confirmação de conta, resposta ao formulário de contato, convites, avisos importantes sobre sua assinatura, e o boletim semanal opcional com o resumo da sua semana (ver seção 3). Usamos o Web Push (um recurso padrão de navegador, entregue pelo serviço de notificações do seu próprio navegador ou sistema operacional) pra enviar o lembrete diário de leitura, quando você ativa esse recurso. Você pode desativar o boletim semanal e os lembretes push a qualquer momento em Perfil.',
      },
      {
        heading: '5. Formulário de Contato',
        body: 'Se você usar o formulário "Fale Conosco" — dentro do app ou no site — guardamos o nome, e-mail e mensagem que você escrever, só pra podermos te responder. Diferente dos outros dados listados acima, esse não exige uma conta: qualquer visitante do site pode enviar uma mensagem, mesmo sem nunca ter se cadastrado no app. Essas mensagens não ficam visíveis a outros usuários, não são usadas pra nenhuma outra finalidade além de responder você, e não recebem nenhum tratamento automatizado — só são lidas por nós.',
      },
      {
        heading: '6. Onde esses dados ficam guardados',
        body: 'O Jesus\' Corner guarda sua conta e todo o conteúdo listado acima — progresso de leitura, sequência de dias, plano escolhido, pedidos de oração, anotações, estatísticas e status da sua assinatura — em um banco de dados hospedado pelo Supabase Inc., nosso provedor de autenticação e banco de dados. É esse banco de dados compartilhado que permite abrir o Jesus\' Corner em mais de um aparelho (por exemplo, celular e computador) e ver exatamente o mesmo progresso nos dois, com login pelo mesmo e-mail e senha. O Supabase atua como nosso processador de dados: ele guarda essas informações em nosso nome, sob as mesmas regras desta política, e não usa seu conteúdo para nenhuma outra finalidade própria. Sua senha nunca é guardada em texto simples — o Supabase a armazena de forma criptografada (hash), e nem nós temos acesso a ela. Se você apagar sua conta (pelo contato abaixo), seus dados são removidos permanentemente desse banco de dados.',
      },
      {
        heading: '7. O que acontece quando você visita nosso site ou app',
        body: 'Como qualquer site, ao acessar o Jesus\' Corner alguns dados técnicos passam pela nossa infraestrutura de hospedagem (Vercel Inc.) — como endereço IP, tipo de navegador e horário de acesso — usados para entregar o conteúdo, sugerir a moeda inicial da assinatura (reais ou dólares, com base no país detectado — você pode trocar manualmente na tela de assinatura) e por segurança. Usamos o Supabase Inc. (ver seção 6) para autenticação e armazenamento de dados e o Stripe Inc. (ou, no app instalado por uma loja, o sistema de cobrança da própria loja) para processar o pagamento da sua assinatura (ver seção 13). Nenhum desses dados técnicos é combinado com o conteúdo da sua conta para fins de publicidade.',
      },
      {
        heading: '8. Amigos, grupos e desafios',
        body: 'Se você adicionar amigos ou participar de grupos de leitura dentro do app (a aba Comunidade), alguns dados passam a ficar visíveis para outras pessoas, não só para você. Pra quem você adiciona como amigo (ou colega de grupo), seu nome, avatar e mensagem do perfil sempre ficam visíveis. Além disso, seu perfil já nasce público pros seus amigos por padrão (essa é a opção padrão no cadastro, ajustável a qualquer momento em Perfil) — nesse caso, seus amigos também conseguem ver seu progresso geral de leitura, o que você está lendo no momento, em quais grupos você está, e um feed com marcos recentes seus (um livro que você concluiu, um nível que você alcançou, um grupo que você entrou), cada um com a data/hora em que aconteceu. Se preferir, você pode deixar o perfil privado a qualquer momento — nesse caso, só nome, avatar e mensagem continuam visíveis pros amigos, e nada do feed de atividade aparece. Já dentro de um desafio de leitura em grupo (por exemplo, "ler Marcos em 1 semana"), o quanto você já leu daquele desafio específico — nunca o seu progresso pessoal completo da Bíblia, nem suas anotações — sempre fica visível pros outros membros do mesmo grupo, num placar de acompanhamento, independente da configuração de perfil público; e qualquer comentário que você postar no mural de discussão de um grupo fica visível para todos os membros daquele grupo, podendo ser apagado por você mesmo ou por um moderador do grupo. Pedidos de amizade enviados e aceitos também ficam registrados. Você pode sair de um grupo, desfazer uma amizade ou trocar entre perfil público e privado a qualquer momento pelo próprio app.',
      },
      {
        heading: '9. Não vendemos nem compartilhamos seus dados',
        body: 'Não usamos rastreadores de publicidade, não vendemos dados a terceiros e não exibimos anúncios. Não usamos ferramentas de analytics que identifiquem você pessoalmente para fins de publicidade. Isso vale também para os provedores de IA e de e-mail que usamos (ver seções 3 e 4): eles processam a informação só pra prestar o serviço contratado — gerar aquela resposta, entregar aquele e-mail — nunca para treinar modelos próprios com seu conteúdo nem para fins de marketing deles.',
      },
      {
        heading: '10. Cookies',
        body: 'Não usamos cookies de rastreamento ou publicidade. O app usa apenas armazenamento local do navegador, necessário para o funcionamento básico (manter você logado, salvar seu progresso).',
      },
      {
        heading: '11. Retenção e exclusão automática de dados',
        body: 'O conteúdo da sua conta — progresso de leitura, anotações, pedidos de oração, marcações e assinatura — fica guardado enquanto sua conta existir, e é apagado por completo se você excluí-la (ver seção 14). Já alguns dados de apoio, mais pontuais por natureza, são apagados automaticamente depois de um tempo, mesmo sem você pedir: mensagens do formulário de contato após 24 meses, o histórico de conversão do onboarding após 12 meses, o histórico de atividade exibido no feed de amigos após 12 meses, as conversas do chat com IA sobre o texto (ver seção 3) após 60 dias, e notificações internas do app (o sino) após 90 dias.',
      },
      {
        heading: '12. Menores de idade',
        body: 'O Jesus\' Corner é um serviço destinado exclusivamente a maiores de 18 anos. Pedimos a idade no cadastro (ver seção 2) e barramos quem declara ter menos de 18, tanto na tela de criação de conta quanto no servidor. Não coletamos nem tratamos, de forma consciente, dados pessoais de crianças ou adolescentes. Se identificarmos que uma conta foi criada por alguém menor de 18, ela será encerrada e os dados associados, apagados. Se você é pai, mãe ou responsável e acredita que um menor sob sua responsabilidade nos forneceu dados, entre em contato com a Encarregada (ver seção 1) para que a conta seja removida.',
      },
      {
        heading: '13. Pagamentos',
        body: 'O Jesus\' Corner tem um plano grátis e dois planos pagos por assinatura, mensal ou anual, com preço fixo — Premium (R$12,90/mês ou R$119,90/ano, ou US$3,99/mês ou US$34,99/ano) e Premium + IA (R$21,90/mês ou R$199,90/ano, ou US$7,99/mês ou US$74,99/ano); veja o site pra mais detalhes. O plano grátis não envolve pagamento nenhum. Se você assinar um plano pago pelo site ou app web, os dados de pagamento (número do cartão, validade, etc.) são inseridos e processados diretamente pelo Stripe, nosso provedor de pagamentos — nunca vemos nem armazenamos esses dados em nossos próprios sistemas; compartilhamos com o Stripe apenas o necessário pra processar a cobrança, como seu e-mail e um identificador da sua assinatura. Se você assinar pelo app instalado a partir da Google Play Store ou da App Store, o pagamento é processado diretamente pelo sistema de cobrança dessa loja (Google Play Billing ou Apple StoreKit), sob a política de privacidade da própria loja. Em nosso próprio banco de dados guardamos só o status da sua assinatura (ativa, cancelada, etc.), o nível e a moeda escolhidos, a periodicidade (mensal ou anual) e até quando ela vale — nunca os dados do seu cartão. Você escolhe a moeda (reais ou dólares) diretamente na tela de assinatura. Você pode cancelar ou trocar de plano quando quiser direto pelo app (Perfil → Minha assinatura) ou, se assinou por uma loja, pelas configurações de assinatura dessa loja; se assinou pelo Stripe e tiver uma cobrança ativa, o app também te leva a um painel hospedado pelo próprio Stripe, onde dá pra trocar o cartão cadastrado e baixar recibos. Ao cancelar, o acesso ao app continua até o fim do período já pago (ver Termos de Uso, seção 3).',
      },
      {
        heading: '14. Seus direitos (LGPD)',
        body: 'Conforme a Lei Geral de Proteção de Dados (LGPD), você tem direito a acessar, corrigir, portar ou apagar seus dados. Dentro do app, você pode baixar uma cópia de tudo que guardamos sobre você (Perfil → Exportar meus dados), reiniciar seu progresso de leitura a qualquer momento (Perfil → Reiniciar leitura), sair de um grupo, desfazer uma amizade, apagar um comentário ou anotação que você escreveu, desativar o boletim semanal e os lembretes push (Perfil), ou sair da sua conta (Perfil → Sair). Você também pode excluir sua conta por completo a qualquer momento, direto pelo app (Perfil → Excluir conta): seu e-mail, senha, anotações, pedidos de oração privados, progresso e assinatura são apagados de vez do nosso banco de dados. A única exceção são comentários e outros conteúdos que você tenha postado em grupos de leitura — eles continuam visíveis para os outros membros (pra não quebrar a conversa deles), mas totalmente desvinculados da sua identidade. Essa exclusão é imediata e não pode ser desfeita. Se preferir, também pode exercer qualquer desses direitos por e-mail, falando com a Encarregada (ver seção 1); atenderemos em até 15 dias. Se entender que seus direitos não foram atendidos, você também pode apresentar uma reclamação à Autoridade Nacional de Proteção de Dados (ANPD), em gov.br/anpd.',
      },
      {
        heading: '15. Mudanças nesta política',
        body: 'Podemos atualizar esta política conforme o app evolui. Sempre que isso acontecer, atualizaremos a data no topo desta página.',
      },
      {
        heading: '16. Contato',
        body: 'Dúvidas sobre privacidade, ou pra exercer seus direitos como titular de dados, escreva para a Encarregada (Daniela Ziller): info@jesuscorner.app',
      },
    ],
  },
  en: {
    title: 'Privacy Policy',
    updated: 'Last updated: September 2026',
    intro: 'This policy explains what data Jesus\' Corner collects, how it\'s used and stored, and what your rights are. We\'ve written it in plain language — no unnecessary legalese — because we believe privacy only works when it\'s actually understandable.',
    sections: [
      {
        heading: '1. Who we are',
        body: 'Jesus\' Corner is operated by JCORNER DESENVOLVIMENTO DE SOFTWARE LTDA, Brazilian company registration (CNPJ) 68.029.736/0001-26. The Data Protection Officer (Encarregada, under article 41 of Brazil\'s LGPD) is Daniela Ziller, reachable at info@jesuscorner.app. For any privacy questions or to exercise your data-subject rights, use that same contact.',
      },
      {
        heading: '2. What data we collect',
        body: 'To create an account, we ask for your name, email, age, and a strong password (minimum 8 characters, with an uppercase letter, lowercase letter, number, and special character) — your age is only used to confirm you are at least 18 (Jesus\' Corner is intended for people 18 and older — see section 12) and isn\'t shared with other users. If you subscribe to one of the paid plans, we also store your subscription status (active, canceled, the tier — Premium or Premium + AI —, the billing interval and currency you chose, and its current expiration) — see section 13 for payment details. As you use the app, we also record: your reading progress (completed chapters and reflections), daily usage streak, chosen reading plan, preferred language, prayer requests, and the content you write — reading notes, daily reflections, application phrases, verse-specific highlights/markups (with an optional note), and sermon notes (preacher, church, and the Bible passages cited, when you fill them in) —, prayer statistics (how many requests, how many timed prayers), and your progress in thematic and guided studies. You can also, entirely optionally, add a short bio to your profile (your profile picture, when not set, shows your name\'s initials — you can\'t upload your own photo). If you turn on push notification reading reminders, we store the technical data needed for that (your device/browser address with the notification service, time zone, and the time/days you choose). If you use the app\'s social features (the Community tab), we also record friend requests (sent and received), the reading groups you\'re part of, the challenges proposed in those groups, any comments you post on a group\'s discussion board, and a small timestamped history of milestones like books completed, levels reached, and groups joined — see section 8 for who can see this data. We also internally record which step of the guided signup flow each person reaches while creating an account — used only to understand where people drop off and improve that flow, never shared with third parties or used for advertising.',
      },
      {
        heading: '3. AI-powered features',
        body: 'Some Jesus\' Corner features use an AI model to generate content or answer questions: building a reading plan or a study from a topic you type in, answering questions about the Bible text as you read (AI chat), searching your own notes by subject instead of exact word, putting together the summary in your weekly digest from the notes you wrote that week, and reading the Bible text aloud (audio reading and hands-free mode). For each of these features, only the information needed for that specific request is sent — the topic you typed, the question you asked, the relevant notes\' text, or just the Bible passage to be narrated, depending on the feature — through Vercel AI Gateway, which routes the request to the AI model providers currently in use: Anthropic (Claude models) for the text features, and OpenAI for text-to-speech. For the audio narration, what\'s sent is only the chapter\'s Bible text itself — no personal data, none of your notes. That information is used only to generate that specific response, is not used to train third-party models, and is not combined with your other data for advertising purposes. As a safety measure, if a question asked in the text chat suggests risk of self-harm or suicide, the app always shows, alongside the response, contact info for a crisis support line — regardless of what the AI itself responds.',
      },
      {
        heading: '4. Emails and notifications',
        body: 'We use Resend Inc. to send Jesus\' Corner\'s emails — account confirmation, replies to the contact form, invites, important notices about your subscription, and the optional weekly digest summarizing your week (see section 3). We use Web Push (a standard browser feature, delivered through your own browser\'s or operating system\'s notification service) to send the daily reading reminder, when you turn that on. You can turn off the weekly digest and push reminders at any time in Profile.',
      },
      {
        heading: '5. Contact Form',
        body: 'If you use the "Contact Us" form — inside the app or on the site — we store the name, email, and message you write, only so we can reply to you. Unlike the other data listed above, this doesn\'t require an account: any site visitor can send a message, even without ever signing up for the app. These messages aren\'t visible to other users, aren\'t used for any purpose beyond replying to you, and don\'t receive any automated processing — they\'re only read by us.',
      },
      {
        heading: '6. Where this data is stored',
        body: 'Jesus\' Corner stores your account and all the content listed above — reading progress, daily streak, chosen plan, prayer requests, notes, stats, and subscription status — in a database hosted by Supabase Inc., our authentication and database provider. This shared database is what lets you open Jesus\' Corner on more than one device (for example, your phone and your computer) and see the exact same progress on both, by logging in with the same email and password. Supabase acts as our data processor: it stores this information on our behalf, under the same rules described in this policy, and does not use your content for any purpose of its own. Your password is never stored in plain text — Supabase stores it encrypted (hashed), and we ourselves have no access to it. If you delete your account (via the contact below), your data is permanently removed from that database.',
      },
      {
        heading: '7. What happens when you visit our site or app',
        body: 'Like any website, when you access Jesus\' Corner some technical data passes through our hosting infrastructure (Vercel Inc.) — such as IP address, browser type, and access time — used to deliver content, suggest an initial subscription currency (Brazilian reais or US dollars, based on your detected country — you can switch it manually on the subscription screen), and for security. We use Supabase Inc. (see section 6) for authentication and data storage, and Stripe Inc. (or, on the app installed from a store, that store\'s own billing system) to process your subscription payment (see section 13). None of this technical data is combined with your account content for advertising purposes.',
      },
      {
        heading: '8. Friends, groups, and challenges',
        body: 'If you add friends or join reading groups inside the app (the Community tab), some data becomes visible to other people, not just you. Anyone you add as a friend (or share a group with) can always see your name, avatar, and bio. On top of that, your profile starts out public to friends by default (this is the default option at signup, adjustable anytime in Profile) — in that case, your friends can also see your overall reading progress, what you\'re currently reading, which groups you\'re in, and a feed of your recent milestones (a book you finished, a level you reached, a group you joined), each with the date/time it happened. If you\'d prefer, you can switch to a private profile at any time — in that case, only your name, avatar, and bio stay visible to friends, and none of the activity feed shows up. Separately, inside a group reading challenge (for example, "read Mark in 1 week"), how much of that specific challenge you\'ve completed — never your full personal Bible reading progress, nor your notes — is always visible to the other members of the same group, in a shared leaderboard, regardless of your public-profile setting; and any comment you post on a group\'s discussion board is visible to every member of that group, and can be deleted by you or by a group moderator. Sent and accepted friend requests are also stored. You can leave a group, unfriend someone, or switch between a public and private profile at any time from within the app.',
      },
      {
        heading: '9. We don\'t sell or share your data',
        body: 'We don\'t use advertising trackers, don\'t sell data to third parties, and don\'t show ads. We don\'t use analytics tools that identify you personally for advertising purposes. This also applies to the AI and email providers we use (see sections 3 and 4): they process information only to provide the service we hired them for — generating that response, delivering that email — never to train their own models on your content, nor for their own marketing purposes.',
      },
      {
        heading: '10. Cookies',
        body: 'We don\'t use tracking or advertising cookies. The app only uses browser local storage, needed for basic functionality (keeping you logged in, saving your progress).',
      },
      {
        heading: '11. Data retention and automatic deletion',
        body: 'Your account content — reading progress, notes, prayer requests, highlights, and subscription — stays stored for as long as your account exists, and is fully deleted if you delete it (see section 14). Some more incidental, point-in-time data is automatically deleted after a while, even without you asking: contact form messages after 24 months, onboarding conversion history after 12 months, the activity history shown in the friends feed after 12 months, AI text-chat conversations (see section 3) after 60 days, and in-app notifications (the bell) after 90 days.',
      },
      {
        heading: '12. Minors',
        body: "Jesus' Corner is a service intended exclusively for people 18 and older. We ask for your age at signup (see section 2) and block anyone who declares they are under 18, both on the account creation screen and on the server. We do not knowingly collect or process personal data of children or adolescents. If we identify that an account was created by someone under 18, it will be terminated and the associated data deleted. If you are a parent or guardian and believe a minor in your care has provided us with data, contact our Data Protection Officer (see section 1) so the account can be removed.",
      },
      {
        heading: '13. Payments',
        body: "Jesus' Corner has a free plan and two paid subscription plans, monthly or annual, at a fixed price — Premium (R$12.90/mo or R$119.90/yr, or US$3.99/mo or US$34.99/yr) and Premium + AI (R$21.90/mo or R$199.90/yr, or US$7.99/mo or US$74.99/yr); see the site for more details. The free plan involves no payment at all. If you subscribe to a paid plan through the site or web app, payment data (card number, expiration date, etc.) is entered and processed directly by Stripe, our payment provider — we never see or store that data on our own systems; we share with Stripe only what's needed to process billing, such as your email and a subscription identifier. If you subscribe through the app installed from the Google Play Store or App Store, payment is processed directly by that store's own billing system (Google Play Billing or Apple StoreKit), under that store's own privacy policy. In our own database, we store only your subscription status (active, canceled, etc.), the tier and currency you chose, the billing interval (monthly or annual), and its current expiration — never your card details. You choose the currency (Brazilian reais or US dollars) yourself, right on the subscription screen. You can cancel or switch plans anytime from within the app (Profile → My subscription) or, if you subscribed through a store, from that store's subscription settings; if you subscribed through Stripe and have an active charge, the app also takes you to a portal hosted directly by Stripe, where you can update your card on file and download receipts. When you cancel, access to the app continues until the end of the period already paid for (see Terms of Use, section 3).",
      },
      {
        heading: '14. Your rights',
        body: 'Depending on where you live, you may have rights to access, correct, port, or delete your data (for example, under Brazil\'s LGPD or similar laws elsewhere). Inside the app, you can download a copy of everything we store about you (Profile → Export my data), restart your reading progress at any time (Profile → Restart reading), leave a group, unfriend someone, delete a comment or note you wrote, turn off the weekly digest and push reminders (Profile), or log out (Profile → Log out). You can also delete your account entirely at any time, right from the app (Profile → Delete account): your email, password, notes, private prayer requests, progress, and subscription are permanently erased from our database. The one exception is comments and other content you posted in reading groups — they stay visible to other members (so their conversation isn\'t broken), but fully unlinked from your identity. This deletion is immediate and cannot be undone. If you\'d prefer, you can also exercise any of these rights by email, contacting the Data Protection Officer (see section 1); we\'ll handle it within 15 days. If you believe your rights haven\'t been respected, you can also file a complaint with Brazil\'s National Data Protection Authority (ANPD), at gov.br/anpd.',
      },
      {
        heading: '15. Changes to this policy',
        body: 'We may update this policy as the app evolves. Whenever that happens, we\'ll update the date at the top of this page.',
      },
      {
        heading: '16. Contact',
        body: 'Questions about privacy, or to exercise your data-subject rights, write to the Data Protection Officer (Daniela Ziller): info@jesuscorner.app',
      },
    ],
  },
}
